"""rename to restock and modify navigation class

Revision ID: 1fe733dfb696
Revises: d83274593e7e
Create Date: 2024-12-08 20:15:47.306064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe733dfb696'
down_revision = 'd83274593e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('target_area', sa.VARCHAR(length=100), nullable=False),
    sa.Column('target_product', sa.VARCHAR(length=200), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
